version: '3'
services:
  paddle1.0:
    container_name: paddlepaddle-test
    image: paddlepaddle:latest
    volumes:
      - ./program:/work
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    working_dir: /work
    command: python ecv_plate_test.py
    network_mode: host
